name: build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - run: |
          echo BINDEP_VERSION=$(grep bindep requirements.txt | cut -d'=' -f3) >> $GITHUB_ENV
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          tags: |
            quay.io/vexxhost/bindep:latest
            quay.io/vexxhost/bindep:${{ env.BINDEP_VERSION }}
